# Generated by Django 3.2.8 on 2021-10-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarista',
            old_name='codigo_igbe',
            new_name='codigo_ibge',
        ),
    ]
