# Generated by Django 3.2.9 on 2021-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_diarista_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarista',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
