# Generated by Django 3.2.9 on 2021-11-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_diarista_formacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarista',
            old_name='descricao',
            new_name='descriçao',
        ),
        migrations.RenameField(
            model_name='diarista',
            old_name='formacao',
            new_name='formaçao',
        ),
    ]
